### ISSUE TITLE
Fix "No Tests Found" issue

### ISSUE THREAD

**Issue by arschles** [deis/e2e-runner#11]
`kubectl` tries to fetch artifacts (logs, etc...), but it sometimes may fail. This issue is for testing the exit code of the `kubectl` command and failing if it's non-zero.

cc/ @jchauncey

**Comment by jchauncey** [comment]
I was working on a fix that worked liek this: 

``` shell
# Capture e2e run test output
tail_logs_from_e2e_pod
podExitCode=$?
echo "Test pod exited with code:${podExitCode}"

#Collect artifacts
retrive-artifacts
retrieveArtifactsExitCode=$?

#Clean up
delete_lease

exit $(( ${podExitCode} + ${retrieveArtifactsExitCode} ))
```
