### ISSUE TITLE
Make PRs not push new images that will get used in CI

### ISSUE THREAD

**Issue by arschles** [deis/e2e-runner#12]
Currently, all PRs build and push a docker image with the `latest` tag, and CI uses that tag. So, any (or every) CI run may use a PR build of this repo. This issue is for changing that so that builds not from `master` push a different tag

cc/ @jchauncey - is this description right?

**Comment by jchauncey** [comment]
So right now the workflow-test-pr/master jobs use `:latest` when using e2e-runner. We should probably move to canary which we update when a pr is merged into master.

**Comment by arschles** [comment]
@jchauncey does https://github.com/deis/e2e-runner/pull/18 close this?

**Comment by arschles** [comment]
talked to @jchauncey offline and confirmed that #18 closes this.
