### ISSUE TITLE
Proposal: don't fail the run if the cluster lease couldn't be deleted

### ISSUE THREAD

**Issue by arschles** [deis/e2e-runner#19]
Currently, the `run.sh` script will fail the test run if the cluster lease delete operation failed, even if the whole test failed. This issue proposes that we let successful tests succeed, even if the lease delete operation failed. Failed deletion operations will result in the lease in question timing out, so the cluster under lease will be unavailable for lease, and unused, for the duration of the lease, but at least not unavailable forever.

**Comment by mboersma** [comment]
This issue has been worked around for a while thanks to more reliable k8s-claimer behavior.
